package launcher

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
	"unicode/utf8"
)

type PresetOptions struct {
	GPULayers         string
	ContextSize       int
	Pooling           string
	BatchSize         int
	UBatchSize        int
	DisableMmprojAuto bool
	Manual            bool
}

func CollectRouterModels(paths ResolvedPaths) ([]ModelFile, []ModelFile, error) {
	generation, err := ScanModels(paths.Models, GenerationModel, ggufExtension)
	if err != nil {
		return nil, nil, err
	}
	embeddings, err := ScanModels(paths.Embeddings, EmbeddingModel, ggufExtension)
	if err != nil {
		return nil, nil, err
	}
	rerank, err := ScanModels(paths.Rerank, RerankModel, ggufExtension)
	if err != nil {
		return nil, nil, err
	}
	projectors, err := ScanModels(paths.Mmproj, GenerationModel, ggufExtension)
	if err != nil {
		return nil, nil, err
	}
	models := append(append(generation, embeddings...), rerank...)
	sortModels(models)
	if len(models) == 0 {
		return nil, projectors, errors.New("models、embeddings 和 rerank 目录中没有可用于 Router 的 .gguf 模型")
	}
	if err := CheckModelIDConflicts(models); err != nil {
		return nil, nil, err
	}
	return models, projectors, nil
}

func CheckModelIDConflicts(models []ModelFile) error {
	byID := make(map[string][]ModelFile)
	for _, model := range models {
		key := strings.ToLower(model.ID)
		byID[key] = append(byID[key], model)
	}
	var keys []string
	for key, matches := range byID {
		if len(matches) > 1 {
			keys = append(keys, key)
		}
	}
	if len(keys) == 0 {
		return nil
	}
	sort.Strings(keys)
	var lines []string
	for _, key := range keys {
		matches := byID[key]
		lines = append(lines, fmt.Sprintf("%s:", matches[0].ID))
		for _, model := range matches {
			lines = append(lines, fmt.Sprintf("  - [%s] %s", model.Kind, model.Path))
		}
	}
	return fmt.Errorf("Router API model id 使用文件名，发现同名冲突，请重命名后重试:\n%s", strings.Join(lines, "\n"))
}

func RenderRouterPreset(models, projectors []ModelFile, options PresetOptions) (string, error) {
	for _, model := range append(append([]ModelFile{}, models...), projectors...) {
		if err := validatePresetField(model.ID, true); err != nil {
			return "", fmt.Errorf("模型文件名不能安全写入 Router preset %q: %w", model.ID, err)
		}
		if err := validatePresetField(model.Path, false); err != nil {
			return "", fmt.Errorf("模型路径不能安全写入 Router preset %q: %w", model.Path, err)
		}
	}
	var lines []string
	lines = append(lines,
		"; Generated by llama-launcher. Edit the manual preset only.",
		"; API model ids are the GGUF filenames.",
		"version = 1",
		"",
	)
	for _, model := range models {
		lines = append(lines,
			"["+model.ID+"]",
			"model = "+model.Path,
		)
		if options.GPULayers != "" {
			lines = append(lines, "n-gpu-layers = "+options.GPULayers)
		}
		if options.ContextSize > 0 {
			lines = append(lines, fmt.Sprintf("ctx-size = %d", options.ContextSize))
		} else if options.Manual {
			lines = append(lines, "; ctx-size = 8192")
		}
		lines = append(lines, "load-on-startup = false")

		switch model.Kind {
		case GenerationModel:
			if projector := FindMatchingMmproj(model, projectors); projector != nil && !options.DisableMmprojAuto {
				lines = append(lines, "mmproj = "+projector.Path)
			} else if options.Manual {
				lines = append(lines, "; mmproj = C:\\path\\to\\mmproj.gguf")
			}
		case EmbeddingModel:
			lines = append(lines, "embedding = true")
			if options.Pooling != "" {
				lines = append(lines, "pooling = "+options.Pooling)
			}
			if options.BatchSize > 0 {
				lines = append(lines, fmt.Sprintf("batch-size = %d", options.BatchSize))
			}
			if options.UBatchSize > 0 {
				lines = append(lines, fmt.Sprintf("ubatch-size = %d", options.UBatchSize))
			}
		case RerankModel:
			lines = append(lines, "reranking = true")
		}
		lines = append(lines, "")
	}
	return strings.Join(lines, "\n"), nil
}

func validatePresetField(value string, sectionName bool) error {
	if value == "" || !utf8.ValidString(value) {
		return errors.New("内容为空或不是有效 UTF-8")
	}
	if sectionName && (strings.TrimSpace(value) != value || strings.ContainsAny(value, "[]")) {
		return errors.New("section 名不能包含首尾空白、[ 或 ]")
	}
	for _, r := range value {
		if unicode.IsControl(r) {
			return fmt.Errorf("包含控制字符 U+%04X", r)
		}
	}
	return nil
}

func WriteRouterPreset(path, content string, overwrite bool) error {
	directory := filepath.Dir(path)
	root := filepath.Dir(directory)
	if err := validateManagedPath(root, directory, "Router 配置目录", false, true); err != nil {
		return err
	}
	if err := validateManagedPath(root, path, "Router 配置文件", true, false); err != nil {
		return err
	}
	data := []byte(content)
	if overwrite {
		if err := writeFileAtomic(path, data, 0o644); err != nil {
			return fmt.Errorf("无法原子写入 Router 配置 %s: %w", path, err)
		}
		return nil
	}
	if err := writeFileExclusive(path, data, 0o644); err != nil {
		if errors.Is(err, os.ErrExist) {
			return fmt.Errorf("手动 Router 配置已存在，拒绝覆盖: %s（确认后可使用 --force）", path)
		}
		return fmt.Errorf("无法原子创建 Router 配置 %s: %w", path, err)
	}
	return nil
}

func PrepareRouter(paths ResolvedPaths, options PresetOptions) (preset string, usedManual bool, models []ModelFile, err error) {
	models, projectors, err := CollectRouterModels(paths)
	if err != nil {
		return "", false, nil, err
	}
	content, err := RenderRouterPreset(models, projectors, options)
	if err != nil {
		return "", false, nil, err
	}
	if err := WriteRouterPreset(paths.RouterAuto, content, true); err != nil {
		return "", false, nil, err
	}
	if err := validateManagedPath(filepath.Dir(filepath.Dir(paths.RouterManual)), paths.RouterManual, "手动 Router 配置", true, false); err != nil {
		return "", false, nil, err
	}
	if info, statErr := os.Lstat(paths.RouterManual); statErr == nil {
		if info.IsDir() {
			return "", false, nil, fmt.Errorf("手动 Router 配置路径是目录: %s", paths.RouterManual)
		}
		return paths.RouterManual, true, models, nil
	} else if !errors.Is(statErr, os.ErrNotExist) {
		return "", false, nil, fmt.Errorf("无法检查手动 Router 配置 %s: %w", paths.RouterManual, statErr)
	}
	return paths.RouterAuto, false, models, nil
}
