package launcher

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type PresetOptions struct {
	GPULayers   string
	ContextSize int
	Pooling     string
	UBatchSize  int
	Manual      bool
}

func CollectRouterModels(paths ResolvedPaths) ([]ModelFile, []ModelFile, error) {
	generation, err := ScanModels(paths.Models, GenerationModel, ggufExtension)
	if err != nil {
		return nil, nil, err
	}
	embeddings, err := ScanModels(paths.Embeddings, EmbeddingModel, ggufExtension)
	if err != nil {
		return nil, nil, err
	}
	rerank, err := ScanModels(paths.Rerank, RerankModel, ggufExtension)
	if err != nil {
		return nil, nil, err
	}
	projectors, err := ScanModels(paths.Mmproj, GenerationModel, ggufExtension)
	if err != nil {
		return nil, nil, err
	}
	models := append(append(generation, embeddings...), rerank...)
	sortModels(models)
	if len(models) == 0 {
		return nil, projectors, errors.New("models、embeddings 和 rerank 目录中没有可用于 Router 的 .gguf 模型")
	}
	if err := CheckModelIDConflicts(models); err != nil {
		return nil, nil, err
	}
	return models, projectors, nil
}

func CheckModelIDConflicts(models []ModelFile) error {
	byID := make(map[string][]ModelFile)
	for _, model := range models {
		key := strings.ToLower(model.ID)
		byID[key] = append(byID[key], model)
	}
	var keys []string
	for key, matches := range byID {
		if len(matches) > 1 {
			keys = append(keys, key)
		}
	}
	if len(keys) == 0 {
		return nil
	}
	sort.Strings(keys)
	var lines []string
	for _, key := range keys {
		matches := byID[key]
		lines = append(lines, fmt.Sprintf("%s:", matches[0].ID))
		for _, model := range matches {
			lines = append(lines, fmt.Sprintf("  - [%s] %s", model.Kind, model.Path))
		}
	}
	return fmt.Errorf("Router API model id 使用文件名，发现同名冲突，请重命名后重试:\n%s", strings.Join(lines, "\n"))
}

func RenderRouterPreset(models, projectors []ModelFile, options PresetOptions) string {
	var lines []string
	lines = append(lines,
		"; Generated by llama-launcher. Edit the manual preset only.",
		"; API model ids are the GGUF filenames.",
		"version = 1",
		"",
	)
	for _, model := range models {
		lines = append(lines,
			"["+model.ID+"]",
			"model = "+model.Path,
		)
		if options.GPULayers != "" {
			lines = append(lines, "n-gpu-layers = "+options.GPULayers)
		}
		if options.ContextSize > 0 {
			lines = append(lines, fmt.Sprintf("ctx-size = %d", options.ContextSize))
		} else if options.Manual {
			lines = append(lines, "; ctx-size = 8192")
		}
		lines = append(lines, "load-on-startup = false")

		switch model.Kind {
		case GenerationModel:
			if projector := FindMatchingMmproj(model, projectors); projector != nil {
				lines = append(lines, "mmproj = "+projector.Path)
			} else if options.Manual {
				lines = append(lines, "; mmproj = C:\\path\\to\\mmproj.gguf")
			}
		case EmbeddingModel:
			lines = append(lines, "embedding = true")
			if options.Pooling != "" {
				lines = append(lines, "pooling = "+options.Pooling)
			}
			if options.UBatchSize > 0 {
				lines = append(lines, fmt.Sprintf("ubatch-size = %d", options.UBatchSize))
			}
		case RerankModel:
			lines = append(lines, "reranking = true")
		}
		lines = append(lines, "")
	}
	return strings.Join(lines, "\n")
}

func WriteRouterPreset(path, content string, overwrite bool) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("无法创建 Router 配置目录: %w", err)
	}
	flags := os.O_WRONLY | os.O_CREATE
	if overwrite {
		flags |= os.O_TRUNC
	} else {
		flags |= os.O_EXCL
	}
	f, err := os.OpenFile(path, flags, 0o644)
	if errors.Is(err, os.ErrExist) {
		return fmt.Errorf("手动 Router 配置已存在，拒绝覆盖: %s（确认后可使用 --force）", path)
	}
	if err != nil {
		return fmt.Errorf("无法写入 Router 配置 %s: %w", path, err)
	}
	if _, err := f.WriteString(content); err != nil {
		f.Close()
		return fmt.Errorf("无法写入 Router 配置 %s: %w", path, err)
	}
	if err := f.Close(); err != nil {
		return fmt.Errorf("无法关闭 Router 配置 %s: %w", path, err)
	}
	return nil
}

func PrepareRouter(paths ResolvedPaths, options PresetOptions) (preset string, usedManual bool, models []ModelFile, err error) {
	models, projectors, err := CollectRouterModels(paths)
	if err != nil {
		return "", false, nil, err
	}
	content := RenderRouterPreset(models, projectors, options)
	if err := WriteRouterPreset(paths.RouterAuto, content, true); err != nil {
		return "", false, nil, err
	}
	if info, statErr := os.Stat(paths.RouterManual); statErr == nil {
		if info.IsDir() {
			return "", false, nil, fmt.Errorf("手动 Router 配置路径是目录: %s", paths.RouterManual)
		}
		return paths.RouterManual, true, models, nil
	} else if !errors.Is(statErr, os.ErrNotExist) {
		return "", false, nil, fmt.Errorf("无法检查手动 Router 配置 %s: %w", paths.RouterManual, statErr)
	}
	return paths.RouterAuto, false, models, nil
}
